[tool.poetry]
name = "citysolar"
version = "0.1.0"
description = "Solar analysis for the DTCC project"
authors = ["Jens Olsson <jens.olsson@chalmersindustriteknik.se>"]
readme = "README.md"

packages = [{include = "citysolar"}]

[tool.poetry.dependencies]
python = "^3.8"
trimesh = "^3.18.0"
ncollpyde = "^0.19.0"
numpy = "^1.24.1"
pandas = "^1.5.2"
argparse = "^1.4.0"
pvlib = "^0.9.4"
pyglet = "^1.5.27"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
