name: build-tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PYTHON_VERSION: "3.11"
      DTCC_DATA_ROOT: ${{ github.workspace }}/data
      EMBREE_VERSION: "4.3.1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip and install build helpers
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools ninja pytest

      - name: Acquire Embree (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -euxo pipefail
          ARCHIVE="$RUNNER_TEMP/embree.tar.gz"
          curl -L -o "$ARCHIVE" "https://github.com/embree/embree/releases/download/v${EMBREE_VERSION}/embree-${EMBREE_VERSION}.x86_64.linux.tar.gz"
          tar -xzf "$ARCHIVE" -C "$RUNNER_TEMP"
          EMBREE_ROOT="$RUNNER_TEMP/embree-${EMBREE_VERSION}.x86_64.linux"
          echo "embree_DIR=${EMBREE_ROOT}/lib/cmake/embree-${EMBREE_VERSION}" >> "$GITHUB_ENV"
          echo "CMAKE_ARGS=-Dembree_DIR=${EMBREE_ROOT}/lib/cmake/embree-${EMBREE_VERSION}" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=${EMBREE_ROOT}/lib:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"

      - name: Acquire Embree (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -euxo pipefail
          ARCHIVE="$RUNNER_TEMP/embree.zip"
          curl -L -o "$ARCHIVE" "https://github.com/embree/embree/releases/download/v${EMBREE_VERSION}/embree-${EMBREE_VERSION}.x86_64.macosx.zip"
          unzip -q "$ARCHIVE" -d "$RUNNER_TEMP"
          EMBREE_ROOT="$RUNNER_TEMP/embree-${EMBREE_VERSION}.x86_64.macosx"
          echo "embree_DIR=${EMBREE_ROOT}/lib/cmake/embree-${EMBREE_VERSION}" >> "$GITHUB_ENV"
          echo "CMAKE_ARGS=-Dembree_DIR=${EMBREE_ROOT}/lib/cmake/embree-${EMBREE_VERSION}" >> "$GITHUB_ENV"
          echo "DYLD_LIBRARY_PATH=${EMBREE_ROOT}/lib:${DYLD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"

      - name: Acquire Embree (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $archive = Join-Path $env:RUNNER_TEMP 'embree.zip'
          $url = "https://github.com/embree/embree/releases/download/v$($env:EMBREE_VERSION)/embree-$($env:EMBREE_VERSION).x64.vc17.windows.zip"
          Invoke-WebRequest -Uri $url -OutFile $archive
          Expand-Archive -Path $archive -DestinationPath $env:RUNNER_TEMP
          $embreeRoot = Join-Path $env:RUNNER_TEMP ("embree-" + $env:EMBREE_VERSION + ".x64.vc17.windows")
          Add-Content $env:GITHUB_ENV "embree_DIR=$embreeRoot\lib\cmake\embree-$($env:EMBREE_VERSION)"
          Add-Content $env:GITHUB_ENV "CMAKE_ARGS=-Dembree_DIR=$embreeRoot\lib\cmake\embree-$($env:EMBREE_VERSION)"
          Add-Content $env:GITHUB_ENV "PATH=$embreeRoot\bin;$env:PATH"

      - name: Install project
        run: |
          python -m pip install .

      - name: Run tests
        working-directory: tests
        run: |
          pytest
